# Data sources

1. Githhub: [‘swar/nba_api’](https://github.com/swar/nba_api)

Our central data source for this project came from a Python wrapper for the NBA’s public API. This API is written for Python and as a result a large portion of our data clearing and exporting came from Python scripts and notebooks (which will be discussed in more detail later). This API grants access to a wide variety of basketball-focused data, however, our project decided to narrow in on a few of its queries. Most importantly, we pulled the play-by-play data which provides a plethora of data at the moment-by-moment level of NBA games. Each row in this data set corresponds to an event in the game, which falls into 1 of 3 categories. An event can be neutral, such as the beginning and ending of a quarter, or events can favor either of the teams, such as a point scored, a foul committed, turnover etc. In addition to a string description of each event, each row in this data set also contains each team's win probability at that moment in time which is already calculated by the NBA. Although we do not have the exact formula for how this crucial statistic is calculated, it is intuitively some function of point differential and time remaining in the game. This statistic is obviously critical for our analysis, since we are specifically looking at the games where a team had >90% win probability at some point in time and then lost the game. We used this data set to initially pull every single game from the last 4 NBA seasons and identify the games where a ‘choke’ occurred. We also used this data set to pull specific player-related data, in particular, how their performance changed over the course of a game that was classified as a ‘choke’. Additional variables in this dataset include the time remaining in the current period and the scores of each team. More analysis of this dataset will be presented in our Missing values chapter.

2. R Package: [nbastatR](https://www.rdocumentation.org/packages/nbastatR/versions/0.1.10131)

In addition to the Python API to pull play-by-play and time-sensitive player data, we also leveraged the R package nbastatR. We used this data set to get aggregate seasonal data for specific players. We decided to use this data set since it allowed us to pull the data directly into R without needing external Python scripts. While the nba_api dataset does also have player statistics, it made more sense to keep this data in R, for easier formatting for subsequent visualization. This package provides R-access to data sets: NBA Stats API, Basketball Insiders, Basketball-Reference, HoopsHype, and RealGM. Depending on what type of statistic you are interested in finding, it will query one of these data sets. For the sake of our analysis, we will make most use of the NBA Stats API to get player statistics. This dataset contains both season-long as well as per-game stats on player performance metrics such as: season, points, assists, rookie status, turnovers, rebounds, player efficiency. This package allows you to determine whether this data should be in a game-by-game basis or by season. We only used this data set to get seasonal player averages, which will be explained further in our Results. 


