# Interactive component

Description:

The data below is from NBA Playoff Games from 2017-2018 where one team has "choked" as we have described extensively throughout our project.

The data is interactively selected to each playoff game requested, and the following mosaic-like bar chart comes on screen:

Reading the chart - The data is split up on each side of the mosaic first by team, followed by shade as follows:

 - <div style="width:100px;height:20px;background-color:royalblue"></div>Home Team. **Top 3 Scorers**
 - <div style="width:100px;height:20px;background-color:lightskyblue"></div>Home Team. **All Other Scorers**
 - <div style="width:100px;height:20px;background-color:maroon"></div>Visiting Team. **Top 3 Scorers**
 - <div style="width:100px;height:20px;background-color:firebrick"></div>Visiting Team. **All Other Scorers**

The height of the plot is represented by the % of points scored by each category before and after the inflection (or choke) point.Therefor, the addition of all scorers then will ad up to 1.0 for before choke and after choke, respectively.

This kind of data gives an insight into why a team may have choked/ made a comeback. For example, the game that automatically comes up is MIA @ BOS. Before the inflection point, Boston's Top 3 players scored much more than they did after the inflection, and in a similar manner, Miami's bottom players before the choke ended up playing a significant role in the second part of the game.

Note: the @ symbol designates who the home and away teams are in that game. For example MIA @ BOS means that Miami was the home team and Boston was the away team.

<br></br>
``` {css, echo=FALSE}
svg {
    margin-left:auto;
    margin-right:auto;
    display:block;
}
```

<html lang="en">

  <head>
    <meta charset="utf-8">
    <title><Stacked Bar Chart></title>
    <script src="https://d3js.org/d3.v7.js"></script>
  </head>

  <body>
    <select id="selectButton"></select>
    <script>

  // width and height
  var w = 500;
  var h = 400;
  var margin = {top: 25, right: 0, bottom: 25, left: 25}
  var innerWidth = w - margin.left - margin.right;
  var innerHeright = h - margin.top - margin.bottom;
  var games = ['MIA @ BOS', 'MIA @ BOS 2', 'BOS @ TOR',
     'LAC @ DAL', 'LAC @ DEN', 'DEN @ LAC', 'HOU @ OKC',
     'MIL @ MIA', 'ATL @ PHI', 'PHI @ ATL', 'DEN @ POR',
     'UTA @ LAC', 'MIL @ BKN', 'IND @ BOS', 'POR @ DEN',
     'SAS @ DEN', 'GSW @ POR', 'GSW @ POR 2', 'POR @ GSW',
     'LAC @ GSW', 'MIL @ TOR', 'TOR @ MIL', 'OKC @ POR',
     'PHI @ BOS', 'CLE @ TOR', 'CLE @ IND', 'GSW @ HOU',
     'HOU @ GSW', 'PHI @ MIA', 'UTA @ OKC']

  // original data
  var dataset = {
    "MIA @ BOS": [
        {
            "game_pct": 0.47677,
            "season": "2019-20",
            "home_top3_pct": 0.32039,
            "home_bottom_pct": 0.26214,
            "away_top3_pct": 0.29126,
            "away_bottom_pct": 0.12621
        },
        {
            "game_pct": 0.52323,
            "season": "2019-20",
            "home_top3_pct": 0.24038,
            "home_bottom_pct": 0.15385,
            "away_top3_pct": 0.23077,
            "away_bottom_pct": 0.375
        }
    ],
    "MIA @ BOS 2": [
        {
            "game_pct": 0.68374,
            "season": "2019-20",
            "home_top3_pct": 0.37013,
            "home_bottom_pct": 0.16883,
            "away_top3_pct": 0.29221,
            "away_bottom_pct": 0.16883
        },
        {
            "game_pct": 0.31626,
            "season": "2019-20",
            "home_top3_pct": 0.24,
            "home_bottom_pct": 0.14667,
            "away_top3_pct": 0.34667,
            "away_bottom_pct": 0.26667
        }
    ],
    "BOS @ TOR": [
        {
            "game_pct": 0.69024,
            "season": "2019-20",
            "home_top3_pct": 0.33803,
            "home_bottom_pct": 0.21127,
            "away_top3_pct": 0.3662,
            "away_bottom_pct": 0.08451
        },
        {
            "game_pct": 0.30976,
            "season": "2019-20",
            "home_top3_pct": 0.14035,
            "home_bottom_pct": 0.22807,
            "away_top3_pct": 0.15789,
            "away_bottom_pct": 0.47368
        }
    ],
    "LAC @ DAL": [
        {
            "game_pct": 0.32305,
            "season": "2019-20",
            "home_top3_pct": 0.18391,
            "home_bottom_pct": 0.1954,
            "away_top3_pct": 0.35632,
            "away_bottom_pct": 0.26437
        },
        {
            "game_pct": 0.67695,
            "season": "2019-20",
            "home_top3_pct": 0.34254,
            "home_bottom_pct": 0.22099,
            "away_top3_pct": 0.18785,
            "away_bottom_pct": 0.24862
        }
    ],
    "LAC @ DEN": [
        {
            "game_pct": 0.53365,
            "season": "2019-20",
            "home_top3_pct": 0.2906,
            "home_bottom_pct": 0.12821,
            "away_top3_pct": 0.38462,
            "away_bottom_pct": 0.19658
        },
        {
            "game_pct": 0.46635,
            "season": "2019-20",
            "home_top3_pct": 0.36957,
            "home_bottom_pct": 0.30435,
            "away_top3_pct": 0.26087,
            "away_bottom_pct": 0.06522
        }
    ],
    "DEN @ LAC": [
        {
            "game_pct": 0.68204,
            "season": "2019-20",
            "home_top3_pct": 0.36054,
            "home_bottom_pct": 0.18367,
            "away_top3_pct": 0.26531,
            "away_bottom_pct": 0.19048
        },
        {
            "game_pct": 0.31796,
            "season": "2019-20",
            "home_top3_pct": 0.30435,
            "home_bottom_pct": 0.05797,
            "away_top3_pct": 0.37681,
            "away_bottom_pct": 0.26087
        }
    ],
    "HOU @ OKC": [
        {
            "game_pct": 0.58216,
            "season": "2019-20",
            "home_top3_pct": 0.26087,
            "home_bottom_pct": 0.19255,
            "away_top3_pct": 0.37888,
            "away_bottom_pct": 0.1677
        },
        {
            "game_pct": 0.41784,
            "season": "2019-20",
            "home_top3_pct": 0.45714,
            "home_bottom_pct": 0.17143,
            "away_top3_pct": 0.21429,
            "away_bottom_pct": 0.15714
        }
    ],
    "MIL @ MIA": [
        {
            "game_pct": 0.71558,
            "season": "2019-20",
            "home_top3_pct": 0.22152,
            "home_bottom_pct": 0.24051,
            "away_top3_pct": 0.36076,
            "away_bottom_pct": 0.17722
        },
        {
            "game_pct": 0.28442,
            "season": "2019-20",
            "home_top3_pct": 0.47368,
            "home_bottom_pct": 0.26316,
            "away_top3_pct": 0.07018,
            "away_bottom_pct": 0.19298
        }
    ],
    "ATL @ PHI": [
        {
            "game_pct": 0.66887,
            "season": "2020-21",
            "home_top3_pct": 0.43165,
            "home_bottom_pct": 0.15108,
            "away_top3_pct": 0.33094,
            "away_bottom_pct": 0.08633
        },
        {
            "game_pct": 0.33113,
            "season": "2020-21",
            "home_top3_pct": 0.27632,
            "home_bottom_pct": 0.05263,
            "away_top3_pct": 0.36842,
            "away_bottom_pct": 0.30263
        }
    ],
    "PHI @ ATL": [
        {
            "game_pct": 0.50457,
            "season": "2020-21",
            "home_top3_pct": 0.2549,
            "home_bottom_pct": 0.15686,
            "away_top3_pct": 0.37255,
            "away_bottom_pct": 0.21569
        },
        {
            "game_pct": 0.49543,
            "season": "2020-21",
            "home_top3_pct": 0.32673,
            "home_bottom_pct": 0.27723,
            "away_top3_pct": 0.15842,
            "away_bottom_pct": 0.23762
        }
    ],
    "DEN @ POR": [
        {
            "game_pct": 0.65133,
            "season": "2020-21",
            "home_top3_pct": 0.31977,
            "home_bottom_pct": 0.22093,
            "away_top3_pct": 0.32558,
            "away_bottom_pct": 0.13372
        },
        {
            "game_pct": 0.34867,
            "season": "2020-21",
            "home_top3_pct": 0.15942,
            "home_bottom_pct": 0.15942,
            "away_top3_pct": 0.23188,
            "away_bottom_pct": 0.44928
        }
    ],
    "UTA @ LAC": [
        {
            "game_pct": 0.51151,
            "season": "2020-21",
            "home_top3_pct": 0.28,
            "home_bottom_pct": 0.12,
            "away_top3_pct": 0.44,
            "away_bottom_pct": 0.16
        },
        {
            "game_pct": 0.48849,
            "season": "2020-21",
            "home_top3_pct": 0.312,
            "home_bottom_pct": 0.336,
            "away_top3_pct": 0.208,
            "away_bottom_pct": 0.144
        }
    ],
    "MIL @ BKN": [
        {
            "game_pct": 0.599,
            "season": "2020-21",
            "home_top3_pct": 0.38931,
            "home_bottom_pct": 0.0458,
            "away_top3_pct": 0.38168,
            "away_bottom_pct": 0.18321
        },
        {
            "game_pct": 0.401,
            "season": "2020-21",
            "home_top3_pct": 0.46154,
            "home_bottom_pct": 0.16484,
            "away_top3_pct": 0.30769,
            "away_bottom_pct": 0.06593
        }
    ],
    "IND @ BOS": [
        {
            "game_pct": 0.75328,
            "season": "2018-19",
            "home_top3_pct": 0.33553,
            "home_bottom_pct": 0.125,
            "away_top3_pct": 0.29605,
            "away_bottom_pct": 0.24342
        },
        {
            "game_pct": 0.24672,
            "season": "2018-19",
            "home_top3_pct": 0.65789,
            "home_bottom_pct": 0.10526,
            "away_top3_pct": 0.15789,
            "away_bottom_pct": 0.07895
        }
    ],
    "POR @ DEN": [
        {
            "game_pct": 0.35054,
            "season": "2018-19",
            "home_top3_pct": 0.37288,
            "home_bottom_pct": 0.25424,
            "away_top3_pct": 0.30508,
            "away_bottom_pct": 0.0678
        },
        {
            "game_pct": 0.64946,
            "season": "2018-19",
            "home_top3_pct": 0.23358,
            "home_bottom_pct": 0.19708,
            "away_top3_pct": 0.24818,
            "away_bottom_pct": 0.32117
        }
    ],
    "SAS @ DEN": [
        {
            "game_pct": 0.70561,
            "season": "2018-19",
            "home_top3_pct": 0.33582,
            "home_bottom_pct": 0.10448,
            "away_top3_pct": 0.41791,
            "away_bottom_pct": 0.14179
        },
        {
            "game_pct": 0.29439,
            "season": "2018-19",
            "home_top3_pct": 0.22353,
            "home_bottom_pct": 0.42353,
            "away_top3_pct": 0.18824,
            "away_bottom_pct": 0.16471
        }
    ],
    "GSW @ POR": [
        {
            "game_pct": 0.61872,
            "season": "2018-19",
            "home_top3_pct": 0.40936,
            "home_bottom_pct": 0.1345,
            "away_top3_pct": 0.1462,
            "away_bottom_pct": 0.30994
        },
        {
            "game_pct": 0.38128,
            "season": "2018-19",
            "home_top3_pct": 0.21538,
            "home_bottom_pct": 0.15385,
            "away_top3_pct": 0.07692,
            "away_bottom_pct": 0.55385
        }
    ],
    "GSW @ POR 2": [
        {
            "game_pct": 0.50801,
            "season": "2018-19",
            "home_top3_pct": 0.31313,
            "home_bottom_pct": 0.26263,
            "away_top3_pct": 0.20202,
            "away_bottom_pct": 0.22222
        },
        {
            "game_pct": 0.49199,
            "season": "2018-19",
            "home_top3_pct": 0.24545,
            "home_bottom_pct": 0.13636,
            "away_top3_pct": 0.21818,
            "away_bottom_pct": 0.4
        }
    ],
    "POR @ GSW": [
        {
            "game_pct": 0.57547,
            "season": "2018-19",
            "home_top3_pct": 0.31967,
            "home_bottom_pct": 0.11475,
            "away_top3_pct": 0.31148,
            "away_bottom_pct": 0.2541
        },
        {
            "game_pct": 0.42453,
            "season": "2018-19",
            "home_top3_pct": 0.36893,
            "home_bottom_pct": 0.2233,
            "away_top3_pct": 0.18447,
            "away_bottom_pct": 0.2233
        }
    ],
    "LAC @ GSW": [
        {
            "game_pct": 0.54262,
            "season": "2018-19",
            "home_top3_pct": 0.33117,
            "home_bottom_pct": 0.25974,
            "away_top3_pct": 0.22078,
            "away_bottom_pct": 0.18831
        },
        {
            "game_pct": 0.45738,
            "season": "2018-19",
            "home_top3_pct": 0.125,
            "home_bottom_pct": 0.23214,
            "away_top3_pct": 0.32143,
            "away_bottom_pct": 0.32143
        }
    ],
    "MIL @ TOR": [
        {
            "game_pct": 0.67561,
            "season": "2018-19",
            "home_top3_pct": 0.29851,
            "home_bottom_pct": 0.14925,
            "away_top3_pct": 0.3209,
            "away_bottom_pct": 0.23134
        },
        {
            "game_pct": 0.32439,
            "season": "2018-19",
            "home_top3_pct": 0.36667,
            "home_bottom_pct": 0.3,
            "away_top3_pct": 0.08333,
            "away_bottom_pct": 0.25
        }
    ],
    "TOR @ MIL": [
        {
            "game_pct": 0.59722,
            "season": "2018-19",
            "home_top3_pct": 0.42105,
            "home_bottom_pct": 0.13158,
            "away_top3_pct": 0.30702,
            "away_bottom_pct": 0.14035
        },
        {
            "game_pct": 0.40278,
            "season": "2018-19",
            "home_top3_pct": 0.15556,
            "home_bottom_pct": 0.24444,
            "away_top3_pct": 0.34444,
            "away_bottom_pct": 0.25556
        }
    ],
    "OKC @ POR": [
        {
            "game_pct": 0.87032,
            "season": "2018-19",
            "home_top3_pct": 0.31156,
            "home_bottom_pct": 0.15075,
            "away_top3_pct": 0.37186,
            "away_bottom_pct": 0.16583
        },
        {
            "game_pct": 0.12968,
            "season": "2018-19",
            "home_top3_pct": 0.52941,
            "home_bottom_pct": 0.23529,
            "away_top3_pct": 0.23529,
            "away_bottom_pct": 0.0
        }
    ],
    "PHI @ BOS": [
        {
            "game_pct": 0.42482,
            "season": "2017-18",
            "home_top3_pct": 0.24691,
            "home_bottom_pct": 0.12346,
            "away_top3_pct": 0.39506,
            "away_bottom_pct": 0.23457
        },
        {
            "game_pct": 0.57518,
            "season": "2017-18",
            "home_top3_pct": 0.25385,
            "home_bottom_pct": 0.34615,
            "away_top3_pct": 0.25385,
            "away_bottom_pct": 0.14615
        }
    ],
    "CLE @ TOR": [
        {
            "game_pct": 0.54737,
            "season": "2017-18",
            "home_top3_pct": 0.31034,
            "home_bottom_pct": 0.22759,
            "away_top3_pct": 0.30345,
            "away_bottom_pct": 0.15862
        },
        {
            "game_pct": 0.45263,
            "season": "2017-18",
            "home_top3_pct": 0.2,
            "home_bottom_pct": 0.225,
            "away_top3_pct": 0.225,
            "away_bottom_pct": 0.35
        }
    ],
    "CLE @ IND": [
        {
            "game_pct": 0.48485,
            "season": "2017-18",
            "home_top3_pct": 0.24742,
            "home_bottom_pct": 0.16495,
            "away_top3_pct": 0.41237,
            "away_bottom_pct": 0.17526
        },
        {
            "game_pct": 0.51515,
            "season": "2017-18",
            "home_top3_pct": 0.37647,
            "home_bottom_pct": 0.23529,
            "away_top3_pct": 0.23529,
            "away_bottom_pct": 0.15294
        }
    ],
    "GSW @ HOU": [
        {
            "game_pct": 0.4675,
            "season": "2017-18",
            "home_top3_pct": 0.46914,
            "home_bottom_pct": 0.12346,
            "away_top3_pct": 0.2963,
            "away_bottom_pct": 0.11111
        },
        {
            "game_pct": 0.5325,
            "season": "2017-18",
            "home_top3_pct": 0.33036,
            "home_bottom_pct": 0.0625,
            "away_top3_pct": 0.29464,
            "away_bottom_pct": 0.3125
        }
    ],
    "HOU @ GSW": [
        {
            "game_pct": 0.77536,
            "season": "2017-18",
            "home_top3_pct": 0.36842,
            "home_bottom_pct": 0.17105,
            "away_top3_pct": 0.36842,
            "away_bottom_pct": 0.09211
        },
        {
            "game_pct": 0.22464,
            "season": "2017-18",
            "home_top3_pct": 0.25714,
            "home_bottom_pct": 0.02857,
            "away_top3_pct": 0.42857,
            "away_bottom_pct": 0.28571
        }
    ],
    "PHI @ MIA": [
        {
            "game_pct": 0.62146,
            "season": "2017-18",
            "home_top3_pct": 0.3,
            "home_bottom_pct": 0.24286,
            "away_top3_pct": 0.23571,
            "away_bottom_pct": 0.22143
        },
        {
            "game_pct": 0.37854,
            "season": "2017-18",
            "home_top3_pct": 0.23529,
            "home_bottom_pct": 0.14706,
            "away_top3_pct": 0.23529,
            "away_bottom_pct": 0.38235
        }
    ],
    "UTA @ OKC": [
        {
            "game_pct": 0.62676,
            "season": "2017-18",
            "home_top3_pct": 0.2735,
            "home_bottom_pct": 0.11966,
            "away_top3_pct": 0.42735,
            "away_bottom_pct": 0.17949
        },
        {
            "game_pct": 0.37324,
            "season": "2017-18",
            "home_top3_pct": 0.60674,
            "home_bottom_pct": 0.07865,
            "away_top3_pct": 0.17978,
            "away_bottom_pct": 0.13483
        }
    ]
};

  // set up stack method
  var stack = d3.stack()
    .keys([ "home_top3_pct", "home_bottom_pct", "away_top3_pct", "away_bottom_pct" ]);

  // data, stacked
  var series = stack(dataset["MIA @ BOS"]);

  // set up scales
  var xScale = d3.scaleBand()
    .domain(d3.range(dataset["MIA @ BOS"].length))
    .range([0, innerWidth])
    .paddingInner(0.02);

  var yScale = d3.scaleLinear()
    .domain([0,	1])
    .range([350, 0]);
  
  var xAxis = d3.axisBottom()
    .scale(xScale)
    .tickFormat(function (d){ return ["Before", "After"][d]});
  
  var yAxis = d3.axisLeft()
    .scale(yScale);

  d3.select("#selectButton")
    .selectAll("myOptions")
    .data(games)
  .enter()
    .append("option")
    .text(function (d) {return d;})
    .attr("value", function (d) {return d;})

  // create consatnt selection of bar chart colors
  var colors = d3.scaleOrdinal(['royalblue', 'lightskyblue', 'maroon', 'firebrick']);

  // create SVG 
  var svg = d3.select("body")
    .append("svg")
    .attr("width", w)
    .attr("height", h)
    .attr("margin", "0 auto");

  // add a group for each row of data
  var groups = svg.selectAll("g")
    .data(series)
    .enter()
    .append("g")
    .attr("transform", `translate (${margin.left}, ${margin.top})`)
    .attr("id", "category")
    .style("fill", (d, i) => colors(i));

  // add a rect for each data value
  var rects = groups.selectAll("rect")
    .data(d => d)
    .enter()
    .append("rect")
    .attr("x", (d, i) => xScale(i))
    .attr("y", d => yScale(d[1]))
    .attr("height", d => (yScale(d[0]) - yScale(d[1])))
    .attr("width", (d, i) => xScale.bandwidth());
  
  // add axes
  svg.append("g")
    .attr("class", "xAxis")
    .attr("transform", `translate (${margin.left}, ${h - margin.bottom})`)
    .call(xAxis);
  
  svg.append("g")
    .attr("class", "yAxis")
    .attr("transform", `translate (${margin.left}, ${margin.top})`)
    .call(yAxis);

 // need to add an update function here on select change
  function update(selectedGame) {
      var datasetGame = dataset[selectedGame];
     
      var stack = d3.stack()
       .keys([ "home_top3_pct", "home_bottom_pct", "away_top3_pct", "away_bottom_pct" ]);
      
      var gameSeries = stack(datasetGame);



      d3.select("body")
      .selectAll("#category")
      .remove();

      var groups = d3.select("svg")
        .selectAll("#category")
        .data(gameSeries)
        .enter()
        .append("g")
        .attr("transform", `translate (${margin.left}, ${margin.top})`)
        .attr("id", "category")
        .style("fill", (d, i) => colors(i));

    
      var rects = groups.selectAll("rect")
        .data(d => d)
        .enter()
        .append("rect")
        .attr("x", 250)
        .attr("y", 200)
        .attr("height", 100)
        .attr("width", 10)
        .transition()
        .duration(2000)
        .attr("x", (d, i) => xScale(i))
        .attr("y", d => yScale(d[1]))
        .attr("height", d => (yScale(d[0]) - yScale(d[1])))
        .attr("width", (d, i) => xScale.bandwidth());
  
    }
    //  d => (yScale(d[2]) - yScale(d[3]))
    d3.select("#selectButton").on("change", function(d) {
        var selectedGame = d3.select(this).property("value")
        console.log(selectedGame)
        update(selectedGame)
    })
    </script>
  </body>
</html>