# Conclusion


Overall, this project shed light on many of the explanatory variables and relationships for choke-prone and comeback-prone NBA teams. Some notable conclusions include the nature of away teams having far more comebacks than home teams, which largely countered our initial thinking coming into the project. I would have imagined that home teams generate more comebacks, but we were proven wrong. Further, it was interesting to note that the ordering of reasons for chokes differ for chokes that occur on a home court vs. away. Specifically, home teams choke more often due to misses, and away teams choke more often due to fouls. Perhaps there is something about the familiarity of a home area or the energy from a crowd that causes players to make these different mistakes when playing in different locations.

Further, from a player-level standpoint, we noted that choke-prone teams' aggregate players statistics do not by any means stand out as overtly negative (shown in MEM player heat map). However, comeback-prone teams do happen to have aggregate player statistics that are relatively strong (shown in OKC player heat map). In order to better flesh out the negative performance of the choke-prone team players, looking at their points before and after a game's turning point was much more telling than their overall season statistics. Additionally, on Memphis, we saw that while all players perform poorly during a choke, some perform notable worse than others. As a result, its possible that chokes are partially the result of individuals performances. However, for the comeback team, OKC, we saw that comeback efforts are the product of the positive performance of the entire team and it is not the product of a consistent single player.

Having had more time for this project, there are some aspects that could have received more attention. Namely, it we likely should have paid closer attention to in-game injuries when we split the data on pre and post game turning point. After seeing the shape of Adams' distribution curve, it occurred to us that we are likely including the performance of players during games when they may have exited early, or been limited due to injury. 

Further, it would have been a rewarding addition to have made the choke-threshold value vary throughout our analysis. While we had our choke threshold hard coded at 90%, it would have been interesting to see how much our findings would be impacted if this number dropped to 85%, or rather raised to 95%. Additionally, it would have been insightful to have had access to team win probabilities within the 5 minute mark. Although these endings would likely cause significant distortion to our definition of a choke, it would have been enlightening to pursue the data behind the final few moments of basketball games. 
