--- 
title: "NBA Chokes"
author: "Elijah Flomen, Blake Hartung"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Overall viewership of basketball in the United States has skyrocketed over the last few years, most notably rising 34% from last season. Perhaps a driving factor for its demand has to do with the notion that basketball is a sport that is well known for its thrilling endings. Unlike sports such as American football or baseball where it is possible for a single team to hold possession of the game for long periods of time, basketball is unique in that the gameflow is going through a constant start-and-stop pace, allowing for constant and rapid changes of possession. 

As a result of basketball's inherent back-and-forth nature, it is not uncommon for a team to, at some point in the game, have a large probability of winning and then end up losing. In the sports community, if at any point a team has a high percentage of winning and then ends up losing a game, that is referred to as a ‘choke.’ For instance, in the context of basketball, if Team A leads Team B by 20 points going into the fourth quarter (12 minutes remaining) and then Team B ends up winning the game, this can likely be classified as a choke by Team A. Given the pace of basketball’s gameflow, matches often result in chokes and we thought that it would be interesting to investigate the data behind to explain these upset endings. For instance, are there teams that are more ‘choke’ prone than others? Do teams tend to have more comebacks when they play at home vs. when they are playing as a visitor? What are the most common reasons for a team to choke? Can we establish a categorical explanation for a choke, what mistakes did a team make for them to lose after such a large lead? Was it due to their fouls, missed shots, turnovers...? How do the individual player stats on a high choke team compare to league averages? Before we dive into the questions that guided our research, we also needed to make some subjective judgements regarding how we defined a choke and selected our data. One of the most crucial of these decisions being to set the maximum win percent threshold to define a subsequent loss as a choke. For the purposes of this analysis, we determined to set this threshold value to be at 90%. Therefore, if at any point in a game, Team A had a 90% chance of winning the game, but the end result was a loss, then we categorized this event to be a choke for Team A. Throughout this entire analysis, we will reference such instances as ‘chokes’. Also, it must be noted that for each instance of a team who ‘choked’, their opponent also experienced a comeback. Given the symmetrical nature of these two occurrences, we will assume that for every time that Team A. choked against Team B, we will also conclude that Team B had a ‘comeback’ against Team A. 

This project will seek to provide an overview of statistical relationships between a range of variables, all focused around games with improbable endings in basketball, over the last four seasons.


